Repository arsentieva/maximum, pull requests merged in 2020-06, with the labels that each got.

#16 Feature aaron comments
  backend/app.js
  backend/routes/comments.js
Labels: question

#21 Feature aaron seeds
  backend/db/seeders/20200616231951-Stories.js
  backend/db/seeders/20200616232315-Comments.js
Labels: enhancement

#22 add functionality to allow a user record to be updated
  backend/routes/users.js
Labels: enhancement

#24 refactor put stories/:id
  backend/routes/stories.js
  backend/utils.js
Labels: bug

#25 more changes for stories.js and users.js
  backend/routes/stories.js
  backend/routes/users.js
  backend/utils.js
Labels: enhancement

#26 Feature aaron comments
  backend/routes/comments.js
  backend/utils.js
Labels: enhancement

#32 Feature aaron heroku
  backend/app.js
  frontend/public/scripts/index.js
  frontend/public/scripts/log-in.js
  frontend/public/scripts/sign-up.js
  frontend/public/scripts/util.js
Labels: enhancement

#34 Feature aaron heroku
  backend/app.js
  frontend/public/scripts/index.js
  frontend/public/scripts/log-in.js
  frontend/public/scripts/sign-up.js
  frontend/public/scripts/util.js
  frontend/views/log-in.pug
Labels: bug

#35 Development
  backend/app.js
  frontend/public/scripts/index.js
  frontend/public/scripts/log-in.js
  frontend/public/scripts/sign-up.js
  frontend/public/scripts/util.js
  frontend/views/log-in.pug
Labels: bug

#36 Testing
  backend/app.js
  backend/routes/stories.js
  frontend/public/scripts/index.js
  frontend/public/scripts/log-in.js
  frontend/public/scripts/sign-up.js
  frontend/public/scripts/story.js
  frontend/public/scripts/util.js
  frontend/views/index.pug
  frontend/views/layout.pug
  frontend/views/log-in.pug
  frontend/views/sign-up.pug
  frontend/views/story.pug
Labels: enhancement

#37 add user profile
  backend/routes/users.js
  frontend/index.js
  frontend/public/scripts/index.js
  frontend/public/scripts/profile.js
  frontend/public/scripts/story.js
  frontend/views/layout.pug
  frontend/views/profile.pug
Labels: enhancement

#38 Feature aaron comments
  backend/routes/comments.js
  frontend/index.js
  frontend/public/scripts/comments.js
  frontend/public/scripts/index.js
  frontend/public/scripts/log-in.js
  frontend/views/comments.pug
  frontend/views/story.pug
Labels: enhancement

#40 Add user profile view and edit page
  backend/routes/users.js
  frontend/public/scripts/profile.js
  frontend/views/profile.pug
Labels: enhancement

#41 stub front end files for new-story functionality
  frontend/index.js
  frontend/public/scripts/new-story.js
  frontend/public/scripts/profile.js
  frontend/views/new-story.pug
  frontend/views/profile.pug
Labels: enhancement

#43 Feature aaron comments
  backend/routes/comments.js
  frontend/index.js
  frontend/public/scripts/comments.js
  frontend/views/comments.pug
  frontend/views/layout.pug
Labels: enhancement

#44 Feature story
  frontend/public/scripts/new-story.js
  frontend/views/new-story.pug
Labels: enhancement

#45 Implement follow/ unfollow of author
  backend/app.js
  backend/routes/follows.js
  backend/routes/stories.js
  frontend/public/scripts/new-story.js
  frontend/public/scripts/story.js
Labels: enhancement

#46 add user followers and following counts on the user profile page
  backend/routes/stories.js
  backend/routes/users.js
  frontend/public/scripts/profile.js
Labels: enhancement

#47 Feature aaron story claps
  backend/app.js
  backend/routes/claps.js
  backend/routes/comments.js
  backend/routes/stories.js
  frontend/public/scripts/story.js
Labels: enhancement, good first issue

#49 Feature aaron story claps
  backend/routes/claps.js
  frontend/public/scripts/story.js
  frontend/public/styles/story.css
Labels: enhancement, help wanted

#51 Feature aaron story claps
  frontend/public/scripts/story.js
  frontend/public/scripts/util.js
Labels: enhancement, good first issue

#48 Development
  backend/app.js
  backend/db/seeders/20200616231951-Stories.js
  backend/routes/claps.js
  backend/routes/comments.js
  backend/routes/follows.js
  backend/routes/stories.js
  backend/routes/users.js
  frontend/index.js
  frontend/public/images/profile-images/1.jpg
  frontend/public/images/profile-images/2.jpg
  frontend/public/images/profile-images/3.jpg
  frontend/public/images/profile-images/4.jpg
  frontend/public/images/profile-images/5.jpg
  frontend/public/images/profile-images/6.jpg
  frontend/public/images/profile-images/temp.jpg
  frontend/public/images/resources/clap.png
  frontend/public/images/resources/log-in-background.jpg
  frontend/public/scripts/comments.js
  frontend/public/scripts/index.js
  frontend/public/scripts/log-in.js
  frontend/public/scripts/log-out.js
  frontend/public/scripts/new-story.js
  frontend/public/scripts/profile.js
  frontend/public/scripts/sign-up.js
  frontend/public/scripts/story.js
  frontend/public/scripts/util.js
  frontend/public/styles/comments.css
  frontend/public/styles/log-in.css
  frontend/public/styles/profile.css
  frontend/public/styles/story.css
  frontend/public/styles/style.css
  frontend/views/comments.pug
  frontend/views/index.pug
  frontend/views/layout.pug
  frontend/views/log-in.pug
  frontend/views/new-story.pug
  frontend/views/profile.pug
  frontend/views/story.pug
Labels: enhancement

#55 Add StoryClaps and Follows seed files and Update Users, Stories, and …
  backend/db/seeders/20200616231928-Users.js
  backend/db/seeders/20200616231951-Stories.js
  backend/db/seeders/20200616232315-Comments.js
  backend/db/seeders/20200623034206-StoryClaps.js
  backend/db/seeders/20200623034235-Follows.js
Labels: enhancement
